### ISSUE TITLE
添加评论时候报错 Board not found

### ISSUE THREAD

**Issue by ZhangXiaoyu-Chief** [michaelliao/itranswarp.js#14]
[2016-12-14T09:39:13.331Z] POST /api/comments/wiki/00148170165015348eed4f326694f0faeaddd40146689f1000
[API Request]
{
  "tag": "wikiffffffffffffffffffffffffff",
  "name": "asdfas",
  "content": "大是打发斯蒂芬"
}
17:39:13.332 [Warp@ca6d3618] CONNECTION: opened from pool: 1
17:39:13.332 [Warp@ca6d3618] SQL: select `id`, `cover_id`, `content_id`, `views`, `name`, `tag`, `description`, `created_at`, `updated_at`, `version` from `wikis` where `id`='00148170165015348eed4f326694f0faeaddd40146689f1000' 
17:39:13.332 [Warp@ca6d3618] CONNECTION: released to pool: 0
17:39:13.333 [Warp@ca6d3618] CONNECTION: opened from pool: 1
17:39:13.333 [Warp@ca6d3618] SQL: select `id`, `topics`, `locked`, `tag`, `name`, `description`, `display_order`, `created_at`, `updated_at`, `version` from `boards`  order by display_order
17:39:13.333 [Warp@ca6d3618] CONNECTION: released to pool: 0
X-Execution-Time: 3
[Error] error when handle url: /api/comments/wiki/00148170165015348eed4f326694f0faeaddd40146689f1000
undefined
[API Response]
{
  "error": "entity:notfound",
  "data": "Board",
  "message": "Board not found."
}

**Comment by michaelliao** [comment]
board和wiki的tag要对上
