### ISSUE TITLE
请教忙看看访问页面报404错的问题

### ISSUE THREAD

**Issue by 18609170116** [michaelliao/itranswarp.js#20]
node.js版本是v7.7.1
启动时日志如下：
c:\MY_JOB\GitHub\itranswarp.js\www>node --harmony app.js
loading config_development...
configuration loaded:
{
  "domain": "www.maoqiongonline.cn",
  "theme": "default",
  "session": {
    "cookie": "isession",
    "salt": "iTranswarp.js",
    "expires": 604800,
    "httpsForManagement": false
  },
  "db": {
    "host": "localhost",
    "port": 3306,
    "user": "root",
    "password": "whosyourdaddy",
    "database": "itranswarp",
    "connectTimeout": 3000,
    "connectionLimit": 20,
    "acquireTimeout": 3000,
    "queueLimit": 10
  },
  "cdn": {
    "static_prefix": ""
  },
  "cache": {
    "prefix": "it/",
    "host": "127.0.0.1",
    "port": 11211,
    "timeout": 1000,
    "retries": 3
  },
  "queue": {
    "host": "127.0.0.1",
    "port": 6379
  },
  "search": {
    "provider": "site_search",
    "configs": {
      "search_url": "http://www.baidu.com/s?ie=utf-8&wd=%s"
    }
  },
  "oauth2": {},
  "END": "END",
  "version": "1.0",
  "build": "$BUILD$"
}
init mysql with mysql-warp...
[Pool@dd3b44e3] Connection pool created.
found model: article
found model: attachment
found model: authuser
found model: board
found model: category
found model: comment
found model: localuser
found model: navigation
found model: random
found model: reply
found model: resource
found model: setting
found model: text
found model: topic
found model: user
found model: webpage
found model: wiki
found model: wikipage
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x---deprecated app.js:55:9
Load i18n file: ./views/i18n/zh_CN.json
Locale zh_CN loaded.
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x---deprecated app.js:104:5
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x---deprecated app.js:112:5
init memcache...
build search engine: site_search
external: true
default settings:
{
    "website": {
        "name": "My Website",
        "description": "Powered by iTranswarp.js",
        "keywords": "",
        "xmlns": "",
        "custom_header": "",
        "custom_footer": ""
    },
    "snippets": {
        "body_top": "",
        "body_bottom": "",
        "sidebar_left_top": "",
        "sidebar_left_bottom": "",
        "sidebar_right_top": "",
        "sidebar_right_bottom": "",
        "content_top": "",
        "content_bottom": ""
    }
}
Not a route definition: $getRecentArticles
Not a route definition: $getArticlesByCategory
Not a route definition: $getAllArticles
Not a route definition: $getArticles
Not a route definition: $getArticle
found: GET /feed in articleApi.js
found route: GET /feed
found: GET /api/articles/:id in articleApi.js
found route: GET /api/articles/:id
found: GET /api/articles in articleApi.js
found route: GET /api/articles
found: POST /api/articles in articleApi.js
found route: POST /api/articles
found: POST /api/articles/:id in articleApi.js
found route: POST /api/articles/:id
found: POST /api/articles/:id/delete in articleApi.js
found route: POST /api/articles/:id/delete
Not a route definition: $getAttachment
Not a route definition: $getAttachments
Not a route definition: $createAttachment
found: GET /files/attachments/:id in attachmentApi.js
found route: GET /files/attachments/:id
found: GET /files/attachments/:id/:size in attachmentApi.js
found route: GET /files/attachments/:id/:size
found: GET /api/attachments/:id in attachmentApi.js
found route: GET /api/attachments/:id
found: GET /api/attachments in attachmentApi.js
found route: GET /api/attachments
found: POST /api/attachments/:id/delete in attachmentApi.js
found route: POST /api/attachments/:id/delete
found: POST /api/attachments in attachmentApi.js
found route: POST /api/attachments
Not a route definition: $getCategories
Not a route definition: $getCategory
Not a route definition: $getNavigationMenus
found: GET /api/categories in categoryApi.js
found route: GET /api/categories
found: GET /api/categories/:id in categoryApi.js
found route: GET /api/categories/:id
found: POST /api/categories in categoryApi.js
found route: POST /api/categories
WARNING: invalid doc line: @param {string,optional} description - The description of the category.
found: POST /api/categories/all/sort in categoryApi.js
found route: POST /api/categories/all/sort
found: POST /api/categories/:id in categoryApi.js
found route: POST /api/categories/:id
found: POST /api/categories/:id/delete in categoryApi.js
found route: POST /api/categories/:id/delete
Not a route definition: $getNavigationMenus
Not a route definition: $createTopic
Not a route definition: $getBoard
Not a route definition: $getBoardByTag
Not a route definition: $getBoards
Not a route definition: $getTopic
Not a route definition: $getTopics
Not a route definition: $getTopicsByRef
Not a route definition: $getReplies
Not a route definition: $getFirstReplies
Not a route definition: $getReplyPageIndex
found: GET /api/ref/:id/topics in discussApi.js
found route: GET /api/ref/:id/topics
found: GET /api/boards in discussApi.js
found route: GET /api/boards
found: POST /api/boards in discussApi.js
found route: POST /api/boards
found: GET /api/boards/:id in discussApi.js
found route: GET /api/boards/:id
WARNING: no api docs found for api: /api/boards/:id
found: POST /api/boards/:id in discussApi.js
found route: POST /api/boards/:id
found: POST /api/boards/:id/lock in discussApi.js
found route: POST /api/boards/:id/lock
found: POST /api/boards/:id/unlock in discussApi.js
found route: POST /api/boards/:id/unlock
found: POST /api/boards/all/sort in discussApi.js
found route: POST /api/boards/all/sort
found: GET /api/boards/:id/topics in discussApi.js
found route: GET /api/boards/:id/topics
found: POST /api/boards/:id/topics in discussApi.js
found route: POST /api/boards/:id/topics
found: GET /api/topics in discussApi.js
found route: GET /api/topics
found: GET /api/replies in discussApi.js
found route: GET /api/replies
found: POST /api/replies/:id/delete in discussApi.js
found route: POST /api/replies/:id/delete
found: POST /api/topics/:id/delete in discussApi.js
found route: POST /api/topics/:id/delete
found: POST /api/topics/:id/replies in discussApi.js
found route: POST /api/topics/:id/replies
found: GET / in home.js
found route: GET /
found: GET /category/:id in home.js
found route: GET /category/:id
found: GET /article/:id in home.js
found route: GET /article/:id
found: GET /webpage/:alias in home.js
found route: GET /webpage/:alias
found: GET /wikipage/:id in home.js
found route: GET /wikipage/:id
found: GET /wiki/:id in home.js
found route: GET /wiki/:id
found: GET /wiki/:wid/:pid in home.js
found route: GET /wiki/:wid/:pid
found: POST /api/comments/:ref_type/:ref_id in home.js
found route: POST /api/comments/:ref_type/:ref_id
WARNING: no api docs found for api: /api/comments/:ref_type/:ref_id
found: GET /discuss in home.js
found route: GET /discuss
found: GET /discuss/:id in home.js
found route: GET /discuss/:id
found: GET /discuss/:bid/:tid in home.js
found route: GET /discuss/:bid/:tid
found: GET /discuss/:bid/topics/create in home.js
found route: GET /discuss/:bid/topics/create
found: GET /discuss/topic/:tid/find/:rid in home.js
found route: GET /discuss/topic/:tid/find/:rid
found: GET /user/:id in home.js
found route: GET /user/:id
found: GET /me/profile in home.js
found route: GET /me/profile
found: GET /auth/signin in home.js
found route: GET /auth/signin
found: GET /search in home.js
found route: GET /search
found: GET /manage/signin in manage.js
found route: GET /manage/signin
found: GET /manage/ in manage.js
found route: GET /manage/
found: GET /manage/overview/(index)? in manage.js
found route: GET /manage/overview/(index)?
found: GET /manage/article/(article_list)? in manage.js
found route: GET /manage/article/(article_list)?
found: GET /manage/article/category_list in manage.js
found route: GET /manage/article/category_list
found: GET /manage/article/create_article in manage.js
found route: GET /manage/article/create_article
found: GET /manage/article/edit_article in manage.js
found route: GET /manage/article/edit_article
found: GET /manage/article/create_category in manage.js
found route: GET /manage/article/create_category
found: GET /manage/article/edit_category in manage.js
found route: GET /manage/article/edit_category
found: GET /manage/webpage/(webpage_list)? in manage.js
found route: GET /manage/webpage/(webpage_list)?
found: GET /manage/webpage/create_webpage in manage.js
found route: GET /manage/webpage/create_webpage
found: GET /manage/webpage/edit_webpage in manage.js
found route: GET /manage/webpage/edit_webpage
found: GET /manage/wiki/(wiki_list)? in manage.js
found route: GET /manage/wiki/(wiki_list)?
found: GET /manage/wiki/create_wiki in manage.js
found route: GET /manage/wiki/create_wiki
found: GET /manage/wiki/edit_wiki in manage.js
found route: GET /manage/wiki/edit_wiki
found: GET /manage/wiki/wiki_tree in manage.js
found route: GET /manage/wiki/wiki_tree
found: GET /manage/wiki/edit_wikipage in manage.js
found route: GET /manage/wiki/edit_wikipage
found: GET /manage/discuss/(board_list)? in manage.js
found route: GET /manage/discuss/(board_list)?
found: GET /manage/discuss/create_board in manage.js
found route: GET /manage/discuss/create_board
found: GET /manage/discuss/edit_board in manage.js
found route: GET /manage/discuss/edit_board
found: GET /manage/discuss/reply_list in manage.js
found route: GET /manage/discuss/reply_list
found: GET /manage/discuss/topic_list in manage.js
found route: GET /manage/discuss/topic_list
found: GET /manage/attachment/(attachment_list)? in manage.js
found route: GET /manage/attachment/(attachment_list)?
found: GET /manage/user/(user_list)? in manage.js
found route: GET /manage/user/(user_list)?
found: GET /manage/navigation/(navigation_list)? in manage.js
found route: GET /manage/navigation/(navigation_list)?
found: GET /manage/navigation/create_navigation in manage.js
found route: GET /manage/navigation/create_navigation
found: GET /manage/setting/ in manage.js
found route: GET /manage/setting/
found: GET /manage/setting/:g in manage.js
found route: GET /manage/setting/:g
Not a route definition: $getNavigation
Not a route definition: $getNavigations
found: GET /api/navigations/all/menus in navigationApi.js
found route: GET /api/navigations/all/menus
found: GET /api/navigations in navigationApi.js
found route: GET /api/navigations
found: POST /api/navigations in navigationApi.js
found route: POST /api/navigations
found: POST /api/navigations/all/sort in navigationApi.js
found route: POST /api/navigations/all/sort
found: POST /api/navigations/:id/delete in navigationApi.js
found route: POST /api/navigations/:id/delete
Not a route definition: $getNavigationMenus
Not a route definition: $getSettings
Not a route definition: $getSetting
Not a route definition: $setSetting
Not a route definition: $setSettings
Not a route definition: $getSettingsByDefaults
Not a route definition: $getWebsiteSettings
Not a route definition: $getSnippets
found: GET /api/settings/definitions in settingApi.js
found route: GET /api/settings/definitions
WARNING: no api docs found for api: /api/settings/definitions
found: GET /api/settings/website in settingApi.js
found route: GET /api/settings/website
WARNING: no api docs found for api: /api/settings/website
found: POST /api/settings/website in settingApi.js
found route: POST /api/settings/website
WARNING: no api docs found for api: /api/settings/website
found: GET /api/settings/snippets in settingApi.js
found route: GET /api/settings/snippets
WARNING: no api docs found for api: /api/settings/snippets
found: POST /api/settings/snippets in settingApi.js
found route: POST /api/settings/snippets
WARNING: no api docs found for api: /api/settings/snippets
Not a route definition: $getUser
Not a route definition: $getUsers
Not a route definition: $bindUsers
found: GET /api/users/:id in userApi.js
found route: GET /api/users/:id
WARNING: no api docs found for api: /api/users/:id
found: GET /api/users in userApi.js
found route: GET /api/users
WARNING: no api docs found for api: /api/users
found: POST /api/authenticate in userApi.js
found route: POST /api/authenticate
WARNING: invalid doc line: @param email: Email address, in lower case.
WARNING: invalid doc line: @param passwd: The password, 40-chars SHA1 string, in lower case.
found: GET /auth/signout in userApi.js
found route: GET /auth/signout
found: GET /auth/from/:name in userApi.js
found route: GET /auth/from/:name
found: GET /auth/callback/:name in userApi.js
found route: GET /auth/callback/:name
found: POST /api/users/:id/lock in userApi.js
found route: POST /api/users/:id/lock
WARNING: no api docs found for api: /api/users/:id/lock
Not a route definition: $getNavigationMenus
Not a route definition: $getWebpage
Not a route definition: $getWebpages
Not a route definition: $getWebpageByAlias
found: GET /api/webpages/:id in webpageApi.js
found route: GET /api/webpages/:id
found: GET /api/webpages in webpageApi.js
found route: GET /api/webpages
found: POST /api/webpages in webpageApi.js
found route: POST /api/webpages
found: POST /api/webpages/:id in webpageApi.js
found route: POST /api/webpages/:id
found: POST /api/webpages/:id/delete in webpageApi.js
found route: POST /api/webpages/:id/delete
Not a route definition: $getNavigationMenus
Not a route definition: $getWikiTree
Not a route definition: $getWiki
Not a route definition: $getWikis
Not a route definition: $getWikiPage
found: GET /api/wikis/:id in wikiApi.js
found route: GET /api/wikis/:id
found: GET /api/wikis in wikiApi.js
found route: GET /api/wikis
found: POST /api/wikis in wikiApi.js
found route: POST /api/wikis
found: POST /api/wikis/:id in wikiApi.js
found route: POST /api/wikis/:id
found: POST /api/wikis/:id/wikipages in wikiApi.js
found route: POST /api/wikis/:id/wikipages
found: POST /api/wikis/wikipages/:id in wikiApi.js
found route: POST /api/wikis/wikipages/:id
found: GET /api/wikis/wikipages/:id in wikiApi.js
found route: GET /api/wikis/wikipages/:id
found: GET /api/wikis/:id/wikipages in wikiApi.js
found route: GET /api/wikis/:id/wikipages
found: POST /api/wikis/wikipages/:id/move in wikiApi.js
found route: POST /api/wikis/wikipages/:id/move
found: POST /api/wikis/wikipages/:id/delete in wikiApi.js
found route: POST /api/wikis/wikipages/:id/delete
found: POST /api/wikis/:id/delete in wikiApi.js
found route: POST /api/wikis/:id/delete
application start in development mode at 8080...

中间显示有一些路由没有找到，然后访问http://localhost:8080报404错，后台日志如下：
[2017-03-03T00:41:46.388Z] GET /
X-Execution-Time: 2
X-Execution-Time: 3
[Error] error when handle url: /
NotFoundError: Not Found
    at Object.throw (c:\MY_JOB\GitHub\itranswarp.js\www\node_modules\koa\lib\context.js:91:23)
    at Object.theMiddleware (c:\MY_JOB\GitHub\itranswarp.js\www\app.js:158:23)
    at theMiddleware.next (<anonymous>)
    at onFulfilled (c:\MY_JOB\GitHub\itranswarp.js\www\node_modules\koa\node_modules\koa-convert\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
是版本的原因还是，请指教，谢谢！~

**Comment by michaelliao** [comment]
upgrade to v2.0
