### ISSUE TITLE
廖老师，关于网站，我想请问把navbar调整为向下滚动时隐藏如何

### ISSUE THREAD

**Issue by rthel** [michaelliao/itranswarp.js#22]
这样在看教程时候整个页面就都是课程内容了，一个建议，期待你的回复

**Comment by love125828499** [comment]
好像现在已经正常了。

**Comment by love125828499** [comment]
![qq 20170518081054](https://cloud.githubusercontent.com/assets/19603427/26181289/90103956-3ba1-11e7-9e4b-1e867be13a06.jpg)

**Comment by ckc** [comment]
@love125828499 請教一下，您是用什麽環境的？我按照readme 裝了好幾遍不成功

**Comment by michaelliao** [comment]
search `uk-navbar-attached`:

`<div class="uk-navbar uk-navbar-attached">`

remove this class.
