### ISSUE TITLE
官网使用后体验

### ISSUE THREAD

**Issue by yushk** [michaelliao/itranswarp.js#25]
首先感谢作者制作的教程,给初学者,本人每天都在看Python的教程,感觉学习效果还不错.
使用建议:
1.建议在页面布局上将目录模块和内容页面模块分开.将目录像标题一样固定悬浮在页面上.
在内容模块上滑动鼠标滚轮,目录不随之滚动

**Comment by chenfd99** [comment]
将目录像标题一样固定悬浮在页左边
在内容模块上滑动鼠标滚轮,目录不随之滚动


还有就是node能不能在js板块中分离开来 单独作为一个模块

**Comment by michaelliao** [comment]
考虑中...
