### ISSUE TITLE
Python3教程章节之间取消快捷跳转

### ISSUE THREAD

**Issue by TrophyD** [michaelliao/itranswarp.js#28]
廖老师您好，最近一个月一直在您的python教程中学习，但是发现最近在您优化了左侧教程目录之后，好像每篇小章节的文末已经没有了左右箭头快捷跳转按键，导致每看完一篇都需要人为往上翻到左侧大目录进行点击，感觉这样没有之前方便呢，提供个小小的意见，希望老师能改进改进，同时感谢您这般无私分享各种教程，致敬！

**Comment by michaelliao** [comment]
已加上
