### ISSUE TITLE
如何初始化数据库

### ISSUE THREAD

**Issue by jianghuzai** [michaelliao/itranswarp.js#30]
说明中描述：
Initialize database

Run node schema > init_db.sql to generate initial schema as well as administrator's email and password.

You will get init_db.sql file in current directory. Run this SQL script by:

$ mysql -u root -p < init_db.sql
NOTE: re-run this SQL file will remove all existing data.

已执行操作：
      我装好了node8，复制config_default.js为config_development.js，修改了数据库连接的密码，其他没动，然后在www目录执行了npm install

问题：对于node schema > init_db.sql这个命令我真的看不懂，
首先，应该在什么目录执行这个命令；
其次，不管我是在"www"，还是在"www/script"目录执行，都是cannt find module

**Comment by ykfq** [comment]
node www/script/init-db.js

**Comment by jianghuzai** [comment]
@ykfq 非常谢谢，已经搭建起来了……
