### ISSUE TITLE
less-watch-compiler 提示少了文件

### ISSUE THREAD

**Issue by jianghuzai** [michaelliao/itranswarp.js#31]
D:\Workspaces\nodejs\itranswarp\www>less-watch-compiler static/css/less static/css itranswarp.less
Watching directory for file changes.
Does not exist : static\css\less\uikit\themes\almost-flat\slideshow.less

求解如何解决

**Comment by jianghuzai** [comment]
搞了三个晚上，终于能跑起来了，但是还是没法编译less，前台页面没有任何样子，，，原来想搭建自己的博客这么难的

**Comment by michaelliao** [comment]
参考 script/less.sh

**Comment by jianghuzai** [comment]
@michaelliao 

谢谢你开源的系统

乱搞了一通，终于能把系统跑起来了……

针对这次花了我半个月的业余时间来跑起来的系统，我在搭起来的系统里面写了些笔记。
我的博客网站：[江湖仔blog](http://www.liguanhua.com)
