### ISSUE TITLE
无法加载 itranswarp.css 文件 404错误

### ISSUE THREAD

**Issue by ykfq** [michaelliao/itranswarp.js#32]
我将服务器跑起来了，可是打开网站却不能正确加载  itranswarp.css 文件，提示404错误:
http://ww1.sinaimg.cn/large/6ee6fa3egy1fl1zhd1k41j20lc0k53zj.jpg
http://ww1.sinaimg.cn/large/6ee6fa3egy1fl1zjiqh46j20tt02idfv.jpg

我看了以前的release版本，这个文件都不存在，是否是原文件不存在呢？

**Comment by michaelliao** [comment]
需要运行script/less.sh 把css编译出来

**Comment by kuangcaibao** [comment]
新版的代码，less.sh 放到 www 目录下了
