### ISSUE TITLE
 关于文章更新的问题

### ISSUE THREAD

**Issue by csnikey** [michaelliao/itranswarp.js#33]
你好，看了下廖雪峰的网站使用的这个框架搭建的，想问下这个更新文章是有单独的ui后台可以编辑的么还是和hexo一样，要项目检出来，然后每次要发布的静态博客站点

**Comment by zqfmaster** [comment]
有ui后台可以编辑的

**Comment by csnikey** [comment]
@zqfmaster 这样啊 蛮棒的 是支持markdown格式的么

**Comment by michaelliao** [comment]
<img width="878" alt="2017-11-28 7 33 18" src="https://user-images.githubusercontent.com/470058/33317755-13726ae8-d473-11e7-9fff-cd574005bddb.png">
