### ISSUE TITLE
关于网站数据备份问题

### ISSUE THREAD

**Issue by ykfq** [michaelliao/itranswarp.js#35]
老师好，我如果想要把网站从一个云服务商迁移到另一个云服务商，除了要备份数据库外，还需要备份网站哪些数据才能在另一个地方还原呢？

**Comment by jianghuzai** [comment]
@ykfq 按我所了解，网站所有数据都是保存到了数据库，所以，复制数据库之外，把部署目录copy过去已经差不多了，如果你想保留日志文件就把日志文件一起复制过去。注意日志文件的属组权限等问题，不然有可能导致日志文件写不进去。
