### ISSUE TITLE
关于手机端

### ISSUE THREAD

**Issue by jeff-sun** [michaelliao/itranswarp.js#38]
手机端应该也适配下，这样在上下班的路上也可以看

**Comment by michaelliao** [comment]
当然适配了：

![wechatimg65](https://user-images.githubusercontent.com/470058/33940458-029de200-e04a-11e7-9e1f-29b9f4a2a535.jpeg)

**Comment by michaelliao** [comment]
当然适配了：

![q](https://user-images.githubusercontent.com/470058/33940481-1ba554ae-e04a-11e7-9f3e-82286d5e24f3.jpg)
