### ISSUE TITLE
For generated all.css failed when production

### ISSUE THREAD

**Issue by ckc** [michaelliao/itranswarp.js#43]
root@cdn-jp:/srv/kbckc/www# npm install gulp
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

I tried update so many times, but not work.

Is it my way wrong to generate all.css, all.js?

**Comment by hupinxiao** [comment]
npm install --global gulp  
npm install --global fab

cd src 
sh release_sample.sh

**Comment by ckc** [comment]
Thx, it's work.
but don't know what about the last two about? I couldn't found.
