### ISSUE TITLE
ipad等平板设备阅读体验极差

### ISSUE THREAD

**Issue by c-jimin** [michaelliao/itranswarp.js#47]
ipad等平板设备阅读体验极差

**Comment by JunjieLink** [comment]
主要是导航栏会变成两行。
例如：
![](https://i.loli.net/2018/05/03/5aeb03c0da1b3.jpg)

**Comment by dox1994** [comment]
的确是遇到了这个问题，恳请作者及时修复一下呀，把移动版的尺寸范围加大一下，让ipad上也当作移动版来显示。

**Comment by michaelliao** [comment]
改成自调整了
![img_0149](https://user-images.githubusercontent.com/470058/49693971-e8eb7000-fbbb-11e8-98e5-4d6a82b7dd76.PNG)
