### ISSUE TITLE
can not create schema

### ISSUE THREAD

**Issue by physiii** [michaelliao/itranswarp.js#48]
instructions say to run **node schema > init_db.sql** to create schema

but I get:
 

> $node schema > init_db.sql
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module '/var/www/itranswarp.js/www/schema'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3
> 

I tried npm install schema but get same error

**Comment by apple-han** [comment]
最后怎么解决的呢？我也碰到了 这个问题

**Comment by JUNJIEDREAM** [comment]
建库和初始化表，要先执行script文件夹中的init_db.js 文件，执行时不要忘记修改config_default.js中的数据库密码
