### ISSUE TITLE
蓝色的框框太高了，阅读的时候要不停的滚动翻看

### ISSUE THREAD

**Issue by anandawang** [michaelliao/itranswarp.js#53]
您好，我用chrome阅读您的网页，觉得蓝色的框框太宽了，哪怕用了全屏模式观看，蓝色的抬头框依然存在，希望您能修订一下，在全屏阅读的时候，抬头蓝色标识框隐藏，方便读者，谢谢。

**Comment by michaelliao** [comment]
fixed

**Comment by andyComeOn** [comment]
> 您好，我用chrome阅读您的网页，觉得蓝色的框框太宽了，哪怕用了全屏模式观看，蓝色的抬头框依然存在，希望您能修订一下，在全屏阅读的时候，抬头蓝色标识框隐藏，方便读者，谢谢。

我看了您提的这个issue，没明白您说的哪个蓝色框框？这个项目是一个模板，不是廖雪峰老师的网站采用了这个项目的模板，我在廖雪峰老师的网站没有看到您说的蓝色框框，能详说一下吗？
