### ISSUE TITLE
网页下面发表评论 http code 400

### ISSUE THREAD

**Issue by DeliriousLee** [michaelliao/itranswarp.js#55]
现在是不能评论了吗
![image](https://user-images.githubusercontent.com/24474112/45415583-8e23a480-b6b0-11e8-8108-62129f8bc530.png)

**Comment by kuroikenshi** [comment]
同样遇到了这个问题，会不会是太火爆了服务器撑不住了三天两头宕，所以廖老师就干脆关闭了2333

**Comment by michaelliao** [comment]
cookie过期了，下次修改成友好提示
