### ISSUE TITLE
我初始化数据库的受报错，不知道这个要怎么解决~  求助

### ISSUE THREAD

**Issue by YienCheng** [michaelliao/itranswarp.js#56]
init database...
Exec: mysql -h localhost -u root --password=xxxxx-e "DROP DATABASE IF EXISTS itranswarp;"
Exec: mysql -h localhost -u root --password=xxxxx -e "CREATE DATABASE itranswarp;"
Exec: mysql -h localhost -u root --password=xxxxx -e "GRANT SELECT, INSERT, UPDATE, DELETE ON itranswarp.* TO 'root'@'localhost' IDENTIFIED BY 'xxxxx';"
Error:
Error: Command failed: mysql -h localhost -u root --password=xxxxx -e "GRANT SELECT, INSERT, UPDATE, DELETE ON itranswarp.* TO 'root'@'localhost' IDENTIFIED BY 'xxxxx';"
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements

**Comment by michaelliao** [comment]
https://stackoverflow.com/questions/43094726/your-password-does-not-satisfy-the-current-policy-requirements
