### ISSUE TITLE
Browser issue - CSS not loaded

### ISSUE THREAD

**Issue by ww9980** [michaelliao/itranswarp.js#8]
Thanks for your amazing work! However, I'm experiencing an issue with improper display of the web page. I'm running it locally, and whatever page I load, it does not have CSS, and the bottom of the page says 

`WARNING: You are using an old browser that does not support HTML5. Please choose a modern browser (Chrome / Firefox / Sarafi) to get a good experience.`

I've verified that my browser does not have any problem (FF&Chrome). Could you please offer me some hints on what to do? Thanks.

**Comment by michaelliao** [comment]
check http://.../static/themes/default/css/itranswarp.css in browser
